import { StyleSheet } from 'react-native';
import { AC } from './constants';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AC.bg },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: AC.divider },
  topBarLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  adminBadge: { width: 40, height: 40, borderRadius: 12, backgroundColor: AC.accentDim, justifyContent: 'center', alignItems: 'center' },
  topBarTitle: { fontSize: 18, fontWeight: '700' as const, color: AC.text },
  topBarSub: { fontSize: 12, color: AC.accent, fontWeight: '500' as const },
  topBarSubRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6 },
  syncBadge: { flexDirection: 'row' as const, alignItems: 'center' as const, backgroundColor: AC.accentDim, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, gap: 3 },
  syncText: { fontSize: 9, fontWeight: '600' as const, color: AC.accent },
  signOutBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: AC.redDim, justifyContent: 'center', alignItems: 'center' },
  tabBar: { flexDirection: 'row', paddingHorizontal: 12, paddingVertical: 8, gap: 2, borderBottomWidth: 1, borderBottomColor: AC.divider },
  tab: { flex: 1, flexDirection: 'column', alignItems: 'center', justifyContent: 'center', paddingVertical: 8, borderRadius: 10, gap: 3 },
  tabActive: { backgroundColor: AC.accentDim },
  tabText: { fontSize: 10, fontWeight: '600' as const, color: AC.textMuted },
  tabTextActive: { color: AC.accent },
  scrollView: { flex: 1 },
  scrollContent: { padding: 16, gap: 16 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  statCard: { flex: 1, minWidth: '45%' as unknown as number, backgroundColor: AC.card, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: AC.border },
  statIconWrap: { width: 44, height: 44, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  statValue: { fontSize: 28, fontWeight: '800' as const, letterSpacing: -0.5 },
  statLabel: { fontSize: 12, fontWeight: '500' as const, color: AC.textSecondary, marginTop: 2 },
  sectionCard: { backgroundColor: AC.card, borderRadius: 16, borderWidth: 1, borderColor: AC.border, overflow: 'hidden' },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: AC.divider },
  sectionTitle: { fontSize: 15, fontWeight: '700' as const, color: AC.text },
  activityRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14 },
  activityLabel: { fontSize: 14, color: AC.textSecondary },
  activityValue: { fontSize: 16, fontWeight: '700' as const, color: AC.text },
  activityDivider: { height: 1, backgroundColor: AC.divider, marginLeft: 16 },
  actionRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14, gap: 12 },
  actionText: { flex: 1, fontSize: 14, color: AC.text, fontWeight: '500' as const },
  userRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, gap: 12 },
  userAvatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: AC.accentDim, justifyContent: 'center', alignItems: 'center' },
  userAvatarText: { fontSize: 16, fontWeight: '700' as const, color: AC.accent },
  userInfo: { flex: 1 },
  userName: { fontSize: 14, fontWeight: '600' as const, color: AC.text },
  userEmail: { fontSize: 12, color: AC.textSecondary, marginTop: 1 },
  userDate: { fontSize: 11, color: AC.textMuted, marginTop: 2 },
  userActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  methodBadge: { backgroundColor: AC.purpleDim, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  methodText: { fontSize: 10, fontWeight: '600' as const, color: AC.purple, textTransform: 'uppercase' as const },
  deleteUserBtn: { width: 32, height: 32, borderRadius: 8, backgroundColor: AC.redDim, justifyContent: 'center', alignItems: 'center' },
  emptyState: { alignItems: 'center', paddingVertical: 32, gap: 12 },
  emptyText: { fontSize: 14, color: AC.textMuted },
  emptySubtext: { fontSize: 12, color: AC.textMuted, marginTop: -4 },
  emptyStateSmall: { alignItems: 'center', paddingVertical: 16 },
  contentIcon: { width: 40, height: 40, borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  contentInfo: { flex: 1 },
  contentLabel: { fontSize: 14, fontWeight: '600' as const, color: AC.text },
  contentSub: { fontSize: 12, color: AC.textSecondary, marginTop: 1 },
  dangerBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', margin: 16, paddingVertical: 14, borderRadius: 12, backgroundColor: AC.redDim, gap: 10, borderWidth: 1, borderColor: 'rgba(239, 68, 68, 0.25)' },
  dangerBtnText: { fontSize: 14, fontWeight: '600' as const, color: AC.red },
  settingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14 },
  settingLabel: { fontSize: 14, color: AC.textSecondary },
  settingValue: { fontSize: 14, fontWeight: '600' as const, color: AC.text, maxWidth: '55%' as unknown as number, textAlign: 'right' as const },
  statusBadge: { backgroundColor: AC.accentDim, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  statusText: { fontSize: 12, fontWeight: '600' as const, color: AC.accent },
  notifHint: { paddingHorizontal: 16, paddingVertical: 12 },
  notifHintText: { fontSize: 12, color: AC.textMuted, lineHeight: 18 },
  editableFieldWrap: { paddingHorizontal: 16, paddingVertical: 12 },
  editableLabel: { fontSize: 11, fontWeight: '600' as const, color: AC.textMuted, textTransform: 'uppercase' as const, letterSpacing: 0.5, marginBottom: 6 },
  editableValueRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  editableValue: { fontSize: 14, fontWeight: '500' as const, color: AC.text, flex: 1, marginRight: 8 },
  editInputRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  editInput: { flex: 1, backgroundColor: AC.inputBg, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, fontSize: 14, color: AC.text, borderWidth: 1, borderColor: AC.border },
  editInputMulti: { minHeight: 60, textAlignVertical: 'top' as const },
  editActionBtn: { width: 36, height: 36, borderRadius: 10, backgroundColor: AC.accentDim, justifyContent: 'center', alignItems: 'center' },
  editCancelBtn: { width: 36, height: 36, borderRadius: 10, backgroundColor: AC.redDim, justifyContent: 'center', alignItems: 'center' },
  designInfoRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14, gap: 12 },
  palettesGrid: { flexDirection: 'row', flexWrap: 'wrap', padding: 12, gap: 10 },
  paletteItem: { width: '47%' as unknown as number, backgroundColor: AC.surface, borderRadius: 12, padding: 10, borderWidth: 1.5, borderColor: AC.border },
  paletteItemSelected: { borderColor: AC.accent, backgroundColor: AC.accentDim },
  paletteSwatches: { flexDirection: 'row', gap: 3, marginBottom: 8 },
  paletteSwatch: { flex: 1, height: 28, borderRadius: 6 },
  paletteName: { fontSize: 11, fontWeight: '600' as const, color: AC.textSecondary },
  paletteNameSelected: { color: AC.accent },
  paletteCheck: { position: 'absolute' as const, top: 8, right: 8, width: 20, height: 20, borderRadius: 10, backgroundColor: AC.accentDim, justifyContent: 'center', alignItems: 'center' },
  paletteSection: { paddingBottom: 8 },
  currentPaletteRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, gap: 10 },
  currentPaletteLabel: { fontSize: 12, color: AC.textMuted, fontWeight: '500' as const },
  currentSwatches: { flexDirection: 'row', gap: 4 },
  currentSwatch: { width: 22, height: 22, borderRadius: 6, borderWidth: 1, borderColor: AC.border },
  currentPaletteName: { fontSize: 12, fontWeight: '600' as const, color: AC.text, flex: 1, textAlign: 'right' as const },
  fontPickerWrap: { paddingHorizontal: 16, paddingVertical: 12 },
  fontPickerBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: AC.inputBg, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 11, gap: 10, borderWidth: 1, borderColor: AC.border },
  fontPickerValue: { flex: 1, fontSize: 14, color: AC.text, fontWeight: '500' as const },
  fontDropdown: { marginTop: 8, backgroundColor: AC.surface, borderRadius: 12, borderWidth: 1, borderColor: AC.border, overflow: 'hidden' },
  fontOption: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: AC.divider },
  fontOptionSelected: { backgroundColor: AC.accentDim },
  fontOptionLeft: { flex: 1 },
  fontOptionName: { fontSize: 14, fontWeight: '500' as const, color: AC.text },
  fontOptionNameSelected: { color: AC.accent },
  fontOptionPreview: { fontSize: 12, color: AC.textMuted, marginTop: 2 },
  addBlockBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', margin: 12, paddingVertical: 12, borderRadius: 12, borderWidth: 1.5, borderColor: AC.accent, borderStyle: 'dashed' as const, gap: 8 },
  addBlockBtnText: { fontSize: 14, fontWeight: '600' as const, color: AC.accent },
  blockHidden: { opacity: 0.5 },
  blockSelected: { borderColor: AC.accent, borderWidth: 2 },
  blockHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: AC.divider },
  blockHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  blockTypeIcon: { width: 34, height: 34, borderRadius: 9, justifyContent: 'center', alignItems: 'center' },
  blockHeaderInfo: { flex: 1 },
  blockTitle: { fontSize: 14, fontWeight: '600' as const, color: AC.text },
  blockType: { fontSize: 10, fontWeight: '600' as const, color: AC.textMuted, letterSpacing: 0.5, marginTop: 1 },
  blockMetaRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6, marginTop: 1 },
  blockSelectedLabel: { fontSize: 9, fontWeight: '700' as const, color: AC.accent, backgroundColor: AC.accentDim, paddingHorizontal: 5, paddingVertical: 1, borderRadius: 4, overflow: 'hidden' as const },
  blockAnimBadge: { fontSize: 9, fontWeight: '700' as const, color: AC.purple, backgroundColor: AC.purpleDim, paddingHorizontal: 5, paddingVertical: 1, borderRadius: 4, overflow: 'hidden' as const },
  blockActions: { flexDirection: 'row', gap: 6 },
  blockActionBtn: { width: 30, height: 30, borderRadius: 8, backgroundColor: AC.surface, justifyContent: 'center', alignItems: 'center' },
  blockStyleSummary: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 6, paddingHorizontal: 14, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: AC.divider },
  styleBadge: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 4, backgroundColor: AC.surface, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, borderWidth: 1, borderColor: AC.border },
  styleBadgeDot: { width: 10, height: 10, borderRadius: 3, borderWidth: 1, borderColor: AC.border },
  styleBadgeText: { fontSize: 10, fontWeight: '600' as const, color: AC.textSecondary },
  blockPreview: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 10, gap: 8 },
  blockPreviewText: { fontSize: 12, color: AC.textSecondary, flex: 1 },
  blockImagePreviewRow: { flexDirection: 'row' as const, alignItems: 'center' as const, paddingHorizontal: 14, paddingVertical: 10, gap: 8 },
  blockThumbnail: { width: 40, height: 40, borderRadius: 8 },
  blockFooter: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: AC.divider },
  blockFooterBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 10, gap: 5 },
  blockFooterBtnText: { fontSize: 12, fontWeight: '600' as const },
  mediaRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 12, gap: 10 },
  mediaTypeIcon: { width: 36, height: 36, borderRadius: 9, justifyContent: 'center', alignItems: 'center' },
  mediaInfo: { flex: 1 },
  mediaName: { fontSize: 13, fontWeight: '600' as const, color: AC.text },
  mediaUrl: { fontSize: 11, color: AC.textMuted, marginTop: 2 },
  mediaThumbnail: { width: 36, height: 36, borderRadius: 9 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: AC.bg, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, maxHeight: '70%' as unknown as number },
  modalContentLarge: { maxHeight: '85%' as unknown as number },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  modalTitle: { fontSize: 18, fontWeight: '700' as const, color: AC.text },
  modalScroll: { flex: 1 },
  editorField: { marginBottom: 16 },
  editorLabel: { fontSize: 12, fontWeight: '600' as const, color: AC.textSecondary, marginBottom: 8, textTransform: 'uppercase' as const, letterSpacing: 0.5 },
  editorSectionLabel: { fontSize: 14, fontWeight: '700' as const, color: AC.accent, marginTop: 8, marginBottom: 16, paddingTop: 12, borderTopWidth: 1, borderTopColor: AC.divider },
  editorInput: { backgroundColor: AC.inputBg, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, fontSize: 14, color: AC.text, borderWidth: 1, borderColor: AC.border },
  editorTextArea: { minHeight: 80, textAlignVertical: 'top' as const },
  alignmentRow: { flexDirection: 'row', gap: 8 },
  alignmentBtn: { flex: 1, paddingVertical: 10, borderRadius: 8, backgroundColor: AC.surface, borderWidth: 1, borderColor: AC.border, alignItems: 'center' },
  alignmentBtnSelected: { borderColor: AC.accent, backgroundColor: AC.accentDim },
  alignmentBtnText: { fontSize: 13, fontWeight: '500' as const, color: AC.textSecondary },
  alignmentBtnTextSelected: { color: AC.accent },
  fontSizeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  fontSizeBtn: { width: 42, height: 36, borderRadius: 8, backgroundColor: AC.surface, borderWidth: 1, borderColor: AC.border, justifyContent: 'center', alignItems: 'center' },
  fontSizeBtnSelected: { borderColor: AC.accent, backgroundColor: AC.accentDim },
  fontSizeBtnText: { fontSize: 13, fontWeight: '500' as const, color: AC.textSecondary },
  fontSizeBtnTextSelected: { color: AC.accent },
  saveBlockBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 14, borderRadius: 12, backgroundColor: AC.accent, gap: 8, marginTop: 8 },
  saveBlockBtnText: { fontSize: 15, fontWeight: '700' as const, color: '#0F1923' },
  mediaTypeToggle: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  mediaTypeBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 10, borderRadius: 10, backgroundColor: AC.surface, borderWidth: 1, borderColor: AC.border, gap: 8 },
  mediaTypeBtnActive: { borderColor: AC.accent, backgroundColor: AC.accentDim },
  mediaTypeBtnText: { fontSize: 14, fontWeight: '600' as const, color: AC.textMuted },
  mediaTypeBtnTextActive: { color: AC.accent },
  uploadBtn: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, paddingVertical: 12, borderRadius: 10, borderWidth: 1.5, borderColor: AC.accent, borderStyle: 'dashed' as const, gap: 8, marginBottom: 8 },
  uploadBtnText: { fontSize: 14, fontWeight: '600' as const, color: AC.accent },
  orDividerText: { fontSize: 12, color: AC.textMuted, textAlign: 'center' as const, marginBottom: 8 },
  imagePreviewWrap: { marginTop: 10, borderRadius: 10, overflow: 'hidden' as const, borderWidth: 1, borderColor: AC.border },
  imagePreview: { width: '100%' as unknown as number, height: 160 },
  uploadSection: { marginBottom: 16 },
  uploadSectionTitle: { fontSize: 13, fontWeight: '700' as const, color: AC.text, marginBottom: 10 },
  uploadSourceRow: { flexDirection: 'row' as const, gap: 10 },
  uploadSourceBtn: { flex: 1, flexDirection: 'column' as const, alignItems: 'center' as const, justifyContent: 'center' as const, paddingVertical: 16, borderRadius: 12, backgroundColor: AC.surface, borderWidth: 1, borderColor: AC.border, gap: 8 },
  uploadSourceBtnText: { fontSize: 13, fontWeight: '600' as const, color: AC.text },
  uploadingRow: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, marginTop: 12, gap: 8 },
  uploadingText: { fontSize: 13, color: AC.accent, fontWeight: '500' as const },
  orDivider: { flexDirection: 'row' as const, alignItems: 'center' as const, marginVertical: 12, gap: 10 },
  orDividerLine: { flex: 1, height: 1, backgroundColor: AC.divider },
  orDividerTextModal: { fontSize: 12, fontWeight: '600' as const, color: AC.textMuted },
  previewActionBar: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, backgroundColor: AC.card, borderRadius: 16, borderWidth: 1, borderColor: AC.border, padding: 10 },
  previewActionBtn: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 5, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 8, backgroundColor: AC.surface },
  previewActionBtnDisabled: { opacity: 0.5 },
  previewActionBtnText: { fontSize: 11, fontWeight: '600' as const },
  previewSaveBtn: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 5, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, backgroundColor: AC.accent, marginLeft: 'auto' as const },
  previewSaveBtnDisabled: { backgroundColor: AC.surfaceLight },
  previewSaveBtnText: { fontSize: 11, fontWeight: '700' as const, color: '#0F1923' },
  unsavedBanner: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, backgroundColor: AC.yellowDim, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, borderWidth: 1, borderColor: 'rgba(234, 179, 8, 0.2)' },
  unsavedDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: AC.yellow },
  unsavedText: { fontSize: 13, fontWeight: '600' as const, color: AC.yellow },
  phoneFrame: { backgroundColor: '#FFFFFF', borderRadius: 28, overflow: 'hidden' as const, borderWidth: 3, borderColor: '#2A3A4A', minHeight: 520, maxHeight: 580 },
  phoneStatusBar: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, alignItems: 'center' as const, paddingHorizontal: 20, paddingVertical: 6 },
  phoneStatusTime: { fontSize: 11, fontWeight: '600' as const },
  phoneStatusIcons: { flexDirection: 'row' as const, gap: 3 },
  phoneSignalDot: { width: 4, height: 4, borderRadius: 2 },
  phoneHeader: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 14 },
  phoneHeaderTitle: { fontSize: 18, fontWeight: '700' as const },
  phoneHeaderSub: { fontSize: 12, marginTop: 2 },
  phoneSearchBar: { paddingHorizontal: 12, paddingVertical: 8 },
  phoneSearchInner: { flexDirection: 'row' as const, alignItems: 'center' as const, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 7, borderWidth: 1, gap: 6 },
  phoneSearchText: { fontSize: 12 },
  phoneBody: { flex: 1, paddingHorizontal: 10, paddingTop: 6 },
  phoneTabBar: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-around' as const, paddingVertical: 8, borderTopWidth: 1, backgroundColor: '#FFFFFF' },
  phoneTabItem: { alignItems: 'center' as const, gap: 2 },
  phoneTabLabel: { fontSize: 9, fontWeight: '600' as const },
  previewLegend: { backgroundColor: AC.card, borderRadius: 16, borderWidth: 1, borderColor: AC.border, padding: 14, gap: 10 },
  previewLegendTitle: { fontSize: 13, fontWeight: '700' as const, color: AC.text },
  previewLegendRow: { flexDirection: 'row' as const, gap: 16 },
  previewLegendItem: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6, flex: 1 },
  previewLegendSwatch: { width: 16, height: 16, borderRadius: 4, borderWidth: 1, borderColor: AC.border },
  previewLegendLabel: { fontSize: 11, color: AC.textSecondary, fontWeight: '500' as const },
  pvPageSelector: { backgroundColor: AC.card, borderRadius: 12, borderWidth: 1, borderColor: AC.border, padding: 8 },
  pvPageChip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 10, backgroundColor: AC.surface, borderWidth: 1, borderColor: AC.border },
  pvPageChipActive: { backgroundColor: AC.accentDim, borderColor: AC.accent },
  pvPageChipText: { fontSize: 12, fontWeight: '600' as const, color: AC.textSecondary },
  pvPageChipTextActive: { color: AC.accent },
  historyItem: { flexDirection: 'row' as const, gap: 12, minHeight: 60 },
  historyTimeline: { alignItems: 'center' as const, width: 20 },
  historyDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: AC.surfaceLight, marginTop: 4 },
  historyDotActive: { backgroundColor: AC.accent },
  historyLine: { width: 2, flex: 1, backgroundColor: AC.surfaceLight, marginTop: 4 },
  historyContent: { flex: 1, paddingBottom: 16 },
  historyLabel: { fontSize: 13, fontWeight: '600' as const, color: AC.text },
  historyTime: { fontSize: 11, color: AC.textMuted, marginTop: 2 },
  historyMeta: { fontSize: 10, color: AC.textMuted, marginTop: 1 },
  historyRestoreBtn: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 4, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, backgroundColor: AC.accentDim, alignSelf: 'flex-start' as const, marginTop: 2 },
  historyRestoreText: { fontSize: 11, fontWeight: '600' as const, color: AC.accent },
  creatorContainer: { backgroundColor: AC.card, borderRadius: 16, borderWidth: 1, borderColor: AC.accent, overflow: 'hidden' as const },
  creatorHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: AC.divider, backgroundColor: AC.accentDim },
  creatorTitle: { fontSize: 16, fontWeight: '700' as const, color: AC.accent },
  creatorCloseBtn: { width: 32, height: 32, borderRadius: 8, backgroundColor: AC.surface, justifyContent: 'center' as const, alignItems: 'center' as const },
  creatorSteps: { flexDirection: 'row' as const, paddingHorizontal: 10, paddingVertical: 8, gap: 6, borderBottomWidth: 1, borderBottomColor: AC.divider },
  creatorStepTab: { flex: 1, flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, gap: 5, paddingVertical: 9, borderRadius: 10, backgroundColor: AC.surface, borderWidth: 1, borderColor: AC.border },
  creatorStepTabActive: { backgroundColor: AC.accentDim, borderColor: AC.accent },
  creatorStepText: { fontSize: 12, fontWeight: '600' as const, color: AC.textMuted },
  creatorStepTextActive: { color: AC.accent },
  creatorBody: { maxHeight: 420 },
  creatorSection: { padding: 14 },
  creatorSectionLabel: { fontSize: 11, fontWeight: '700' as const, color: AC.textMuted, textTransform: 'uppercase' as const, letterSpacing: 0.5, marginBottom: 10 },
  creatorTypeGrid: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 8 },
  creatorTypeCard: { width: '47%' as unknown as number, backgroundColor: AC.surface, borderRadius: 12, padding: 12, borderWidth: 1.5, borderColor: AC.border, gap: 6 },
  creatorTypeCardActive: { borderColor: AC.accent, backgroundColor: AC.accentDim },
  creatorTypeIconWrap: { width: 40, height: 40, borderRadius: 10, backgroundColor: AC.surfaceLight, justifyContent: 'center' as const, alignItems: 'center' as const },
  creatorTypeIconWrapActive: { backgroundColor: 'rgba(0, 212, 170, 0.15)' },
  creatorTypeLabel: { fontSize: 13, fontWeight: '600' as const, color: AC.text },
  creatorTypeLabelActive: { color: AC.accent },
  creatorTypeDesc: { fontSize: 10, color: AC.textMuted },
  creatorTypeCheck: { position: 'absolute' as const, top: 8, right: 8, width: 20, height: 20, borderRadius: 10, backgroundColor: AC.accentDim, justifyContent: 'center' as const, alignItems: 'center' as const },
  creatorNextBtn: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, paddingVertical: 12, borderRadius: 10, backgroundColor: AC.accent, gap: 6, marginTop: 16 },
  creatorNextBtnText: { fontSize: 14, fontWeight: '700' as const, color: '#0F1923' },
  creatorPageGrid: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 8 },
  creatorPageChip: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10, backgroundColor: AC.surface, borderWidth: 1.5, borderColor: AC.border },
  creatorPageChipActive: { borderColor: AC.accent, backgroundColor: AC.accentDim },
  creatorPageChipText: { fontSize: 13, fontWeight: '600' as const, color: AC.textSecondary },
  creatorPageChipTextActive: { color: AC.accent },
  creatorBgTypeRow: { flexDirection: 'row' as const, gap: 8 },
  creatorBgTypeBtn: { flex: 1, paddingVertical: 11, borderRadius: 10, backgroundColor: AC.surface, borderWidth: 1.5, borderColor: AC.border, alignItems: 'center' as const },
  creatorBgTypeBtnActive: { borderColor: AC.accent, backgroundColor: AC.accentDim },
  creatorBgTypeBtnText: { fontSize: 12, fontWeight: '600' as const, color: AC.textSecondary },
  creatorBgTypeBtnTextActive: { color: AC.accent },
  creatorColorGrid: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 7 },
  creatorColorSwatch: { width: 32, height: 32, borderRadius: 8, borderWidth: 1.5, borderColor: AC.border, justifyContent: 'center' as const, alignItems: 'center' as const },
  creatorColorSwatchActive: { borderColor: AC.accent, borderWidth: 2.5 },
  creatorInput: { backgroundColor: AC.inputBg, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, fontSize: 14, color: AC.text, borderWidth: 1, borderColor: AC.border },
  creatorCreateBtn: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, paddingVertical: 14, borderRadius: 12, backgroundColor: AC.accent, gap: 8, marginTop: 20 },
  creatorCreateBtnDisabled: { backgroundColor: AC.surfaceLight, opacity: 0.5 },
  creatorCreateBtnText: { fontSize: 15, fontWeight: '700' as const, color: '#0F1923' },
});
